name: Build native

on:
  workflow_dispatch:

jobs:
  build-native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Maven build native
        run: ./mvnw compile -Dnative -DskipTests
  build-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        run: docker build . --file src/main/docker/Dockerfile.native -t quarkus-native-image
